### ISSUE TITLE
It doesn't work as expected with some editors

### ISSUE THREAD

**Issue by stefanos82** [edubart/forkmon#1] opened 2021-06-08 23:24 UTC
Just add the option to remove remove `bin/linux64/forkmon.so` as well.

By the way, I cannot make it work...well, the alias work, but does not monitor :shrug: 

`alias forkmon-nelua='LD_PRELOAD=/PortableApps/forkmon/bin/linux64/forkmon.so FORKMON_FILTER=".nelua$" nelua'`

**Comment by edubart** [comment] 2021-06-08 23:29
> By the way, I cannot make it work...well, the alias work, but does not monitor

Try compiling yourself then, are you using Linux? What distribution?

**Comment by stefanos82** [comment] 2021-06-08 23:34
Yes, I'm on GNU / Debian Linux testing 64-bit, fully updated.

The `make test` works with Lua, but upon edit a file it fails because it cannot find the path when I change `foo` to `bar` in the running test.

Also, see what happens below:

```
stefanos@debian:/PortableApps/forkmon [main]$ LD_PRELOAD=./forkmon.so FORKMON_FILTER="%.lua$" lua /home/stefanos/code/lua/generic.lua 
[forkmon] watch '/home/stefanos/code/lua/generic.lua'
width:	100	height:	100
[forkmon] file '/home/stefanos/code/lua/generic.lua' changed, resuming from it ...
lua: cannot open /home/stefanos/code/lua/generic.lua: No such file or directory


```

**Comment by edubart** [comment] 2021-06-08 23:40
> lua: cannot open /home/stefanos/code/lua/generic.lua: No such file or directory

That is odd..
Maybe the OS did not finish flushing the files to the disk, try using another lightweight code editor to edit and save the file, like `vim`, or increase `FORKMON_RESTART_DELAY` to a large value, like:

```bash
export FORKMON_RESTART_DELAY=200
```

**Comment by stefanos82** [comment] 2021-06-08 23:45
I'm using `vim` exclusively.

I have tried your suggestion and worked just twice and that's it :thinking: 

```
$ LD_PRELOAD=./forkmon.so FORKMON_FILTER="%.lua$" lua /home/stefanos/code/lua/generic.lua 
[forkmon] watch '/home/stefanos/code/lua/generic.lua'
width:	100	height:	100
[forkmon] file '/home/stefanos/code/lua/generic.lua' changed, resuming from it ...
width:	110	height:	100
[forkmon] file '/home/stefanos/code/lua/generic.lua' changed, resuming from it ...
width:	100	height:	100
^CKilled
```

**Comment by edubart** [comment] 2021-06-08 23:54
Nice it worked then, thus I have increased the default from 20ms to 50ms.

Depending on your disk, OS, setup, running applications, saving files can take a few milliseconds before an application can it read successfully, I my case I am using a fast SSD disk, so files saves pretty fast, and 20ms was a reasonable value for me.

**Comment by stefanos82** [comment] 2021-06-08 23:55
I will try it again and let you know.

**Comment by stefanos82** [comment] 2021-06-08 23:58
Nope, still the same issue; it limits me up to 2 changes only! O.o

**Comment by edubart** [comment] 2021-06-09 00:03
> Nope, still the same issue; it limits me up to 2 changes only! O.o

With larger values it always work? I cannot help much without being able to reproduce here, note that this project is experimental, I guess it may not well on all Linux systems then. On mine works flawlessy though.

**Comment by stefanos82** [comment] 2021-06-09 00:07
Nothing; still the same, even with `500`...

```
stefanos@debian:/PortableApps/forkmon [main]$ LD_PRELOAD=./forkmon.so FORKMON_FILTER="%.lua$" FORKMON_RESTART_DELAY=500 lua /home/stefanos/code/lua/generic.lua
[forkmon] watch '/home/stefanos/code/lua/generic.lua'
width:	100	height:	100
[forkmon] file '/home/stefanos/code/lua/generic.lua' changed, resuming from it ...
width:	101	height:	100
[forkmon] file '/home/stefanos/code/lua/generic.lua' changed, resuming from it ...
width:	100	height:	100

```

**Comment by edubart** [comment] 2021-06-09 00:14
What are the values of sysctl inotify configs? Mine as reference:

```bash
$ sudo sysctl -a | grep inotify
fs.inotify.max_queued_events = 16384
fs.inotify.max_user_instances = 1024
fs.inotify.max_user_watches = 524288
user.max_inotify_instances = 1024
user.max_inotify_watches = 524288
```

You could try this:
```bash
sudo sysctl -w user.max_inotify_instances=1024
```

**Comment by stefanos82** [comment] 2021-06-09 00:16
```
fs.inotify.max_queued_events = 16384
fs.inotify.max_user_instances = 128
fs.inotify.max_user_watches = 524288
user.max_inotify_instances = 128
user.max_inotify_watches = 524288
```
Let me check right now.

**Comment by stefanos82** [comment] 2021-06-09 00:18
OK, this is interesting.

After running `sudo sysctl -w user.max_inotify_instances=1024` the results were displayed instantly, but still hangs on 2 outputs only.

**Comment by edubart** [comment] 2021-06-09 00:25
Ok, maybe something is wrong in the code and the bug can be triggered just in your system (or Debian), is quite tricky to manage/understand the code as it spawns and kills multiple children processes. I cannot do much from here, I guess then you should not use this tool there..

**Comment by stefanos82** [comment] 2021-06-09 00:26
Is there any flag for verbosity for forkmon?

It could help to see what it loads during execution.

**Comment by edubart** [comment] 2021-06-09 00:27
There isn't a flag to print more debug messages, you would have to add prints in the code yourself.

**Comment by edubart** [comment] 2021-06-09 00:28
I will give a try into reproducing the issue inside a VM.

**Comment by stefanos82** [comment] 2021-06-09 00:28
Sure thing.

**Comment by stefanos82** [comment] 2021-06-09 00:32
No need to test it on VM; I have found the problem.

It's `vim` that causes the issue.

With `nano` works as expected. It seems `forkmon` does not "see" the undo option as new command.

**Comment by stefanos82** [comment] 2021-06-09 00:34
Nope; I rushed to talk...it still behaves the same with `mousepad`!

**Comment by stefanos82** [comment] 2021-06-09 00:37
This is really **really** weird.

If I kill `forkmon` and restart it, open a file with `nano`, it works as expected.

If I repeat the aforementioned step with `mousepad`, it works **JUST ONCE**! HAHAHAHA :rofl:

**Comment by edubart** [comment] 2021-06-09 00:44
I could reproduce with vim, it works twice as you. The issue is related how the editor save files.

I think I know what it is, I will have to rework the code to support editors that deletes the file and save again, the algorithm is expecting the file to never be deleted, for some reason some editors like to delete and create them again.

**Comment by stefanos82** [comment] 2021-06-09 00:49
Hopefully by tomorrow will test it anew and let you know how it goes.

**Comment by edubart** [comment] 2021-06-09 00:53
I've pushed the fix, luckily it was simple, let me know if things work fine there now.

**Comment by stefanos82** [comment] 2021-06-09 00:58
Until I test it, read [this article](https://dev.to/0xbf/use-inotify-api-to-monitor-file-change-13li); it explains in detail what is happening in our case.

**Comment by stefanos82** [comment] 2021-06-09 01:00
It killed itself while I was editing my Lua file!

```
$ LD_PRELOAD=./forkmon.so FORKMON_FILTER="%.lua$" lua /home/stefanos/code/lua/generic.lua
[forkmon] watch '/home/stefanos/code/lua/generic.lua'
width:	100	height:	100
[forkmon] some file changed, resuming from '/home/stefanos/code/lua/generic.lua' ...
width:	100	height:	200
[forkmon] some file changed, resuming from '/home/stefanos/code/lua/generic.lua' ...
width:	100	height:	100
[forkmon] some file changed, resuming from '/home/stefanos/code/lua/generic.lua' ...
width:	100	height:	101
[forkmon] some file changed, resuming from '/home/stefanos/code/lua/generic.lua' ...
width:	100	height:	100
[forkmon] some file changed, resuming from '/home/stefanos/code/lua/generic.lua' ...
width:	200	height:	100
[forkmon] some file changed, resuming from '/home/stefanos/code/lua/generic.lua' ...
width:	100	height:	100
[forkmon] some file changed, resuming from '/home/stefanos/code/lua/generic.lua' ...
width:	102	height:	100
[forkmon] failed to watch file
Killed
```

**Comment by edubart** [comment] 2021-06-09 01:02
> [forkmon] failed to watch file

The file was probably not found, either  `FORKMON_RESTART_DELAY` is too small there, or the editor is taking too long to save.

**Comment by stefanos82** [comment] 2021-06-09 01:09
I see.

By the way, if you are on Linux, have you tried `watch` command?

I have just tried `watch -n 0.1 lua /home/stefanos/code/lua/generic.lua` and works exactly as `forkmon`.

**Comment by edubart** [comment] 2021-06-09 01:13
> I see.
> 
> By the way, if you are on Linux, have you tried `watch` command?
> 
> I have just tried `watch -n 0.1 lua /home/stefanos/code/lua/generic.lua` and works exactly as `forkmon`.

Yes, but Forkmon restarts from a checkpoint, it's very different, because of this it can skip application processing before the checkpoint, thus speeding up restart. While watch,  `nodemon` or others doesn't. I have also another library that does the same, that one very similar to `nodemon`, the [luamon](https://github.com/edubart/luamon). I personally use `luamon` more often, and `forkmon` for large projects.

**Comment by stefanos82** [comment] 2021-06-09 01:14
Good good!

**Comment by stefanos82** [comment] 2021-06-09 01:16
Now, why I cannot make it work with `nelua`...goes beyond me right now.

**Comment by edubart** [comment] 2021-06-09 11:27
> Now, why I cannot make it work with `nelua`...goes beyond me right now.

I think it could be because Nelua is running through a bash script, I made changes in forkmon to possible solve issues on that.
Try now and see if works. 

If not I would ask to try to execute Nelua manually without its bash script, eg:

```bash
LD_PRELOAD=/projects/forkmon/forkmon.so FORKMON_FILTER="%.nelua$" /projects/nelua/src/nelua-lua -e 'package.path='\''/projects/nelua/?.lua;'\''..package.path' test.nelua
```
Of course you need to adjust the above to your paths.

**Comment by stefanos82** [comment] 2021-06-09 11:59
OK, let me try right now and let you know.

In the meantime, can you add `nelua_cache` in `.gitignore`? `git status` reports it.

**Comment by stefanos82** [comment] 2021-06-09 12:03
Now it works as expected without the alternative solution you shared above.

**Closed as completed** 2021-06-09 15:14 UTC
